services:
  postgres:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_SSL_MODE: ${POSTGRES_SSL_MODE}
    ports:
      - "5433:5432"
    volumes:
      - ./db_creation:/docker-entrypoint-initdb.d  

  jobs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jobs-container
    ports:
      - "8080:8080"  # app port
      - "6060:6060"  # pprof
    depends_on:
      - postgres
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_SSL_MODE: ${POSTGRES_SSL_MODE}
      PYROSCOPE_SERVER_ADDRESS: http://pyroscope:4040
      PYROSCOPE_APPLICATION_NAME: job-seeker-jobs
    volumes:
      - .:/app

  pyroscope:
    image: grafana/pyroscope:latest
    container_name: pyroscope
    ports:
      - "4040:4040" # http://localhost:4040/ pyroscope graphs
    volumes:
      - pyroscope_data:/var/lib/pyroscope 
    command: server

volumes:
  pyroscope_data: